services:
  seafile:
    image: ${SEAFILE_IMAGE:-docker.seadrive.org/seafileltd/seafile-pro-mc:12.0-latest}
    container_name: seafile
    ports:
      - 80:80
    volumes:
      - ${SEAFILE_VOLUME:-/opt/seafile/shared}:/shared
    environment:
      - DB_HOST=${SEAFILE_MYSQL_DB_HOST:-db}
      - DB_PORT=${SEAFILE_MYSQL_DB_PORT:-3306}
      - DB_ROOT_PASSWD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      - DB_PASSWORD=${SEAFILE_MYSQL_DB_PASSWORD:?Variable is not set or empty}
      - CLUSTER_SERVER=true
      - CLUSTER_INIT_MODE=${CLUSTER_INIT_MODE:-false}
      - CLUSTER_INIT_MEMCACHED_HOST=${CLUSTER_MEMCACHED_HOST}
      - CLUSTER_INIT_ES_HOST=${CLUSTER_ES_HOST}
      - CLUSTER_INIT_ES_PORT=${CLUSTER_INIT_ES_PORT}
      - CLUSTER_MODE=${CLUSTER_MODE:-frontend}
      - TIME_ZONE=${TIME_ZONE:-UTC}
      - INIT_S3_STORAGE_BACKEND_CONFIG=${INIT_S3_STORAGE_BACKEND_CONFIG:-false}
      - INIT_S3_COMMIT_BUCKET=${INIT_S3_COMMIT_BUCKET}
      - INIT_S3_FS_BUCKET=${INIT_S3_FS_BUCKET}
      - INIT_S3_BLOCK_BUCKET=${INIT_S3_BLOCK_BUCKET}
      - INIT_S3_KEY_ID=${INIT_S3_KEY_ID}
      - INIT_S3_SECRET_KEY=${INIT_S3_SECRET_KEY}
      - INIT_S3_USE_V4_SIGNATURE=${INIT_S3_USE_V4_SIGNATURE:-true}
      - INIT_S3_AWS_REGION=${INIT_S3_AWS_REGION:-us-east-1}
      - INIT_S3_USE_HTTPS=${INIT_S3_USE_HTTPS:-true}

