services:
  face-embedding:
    image: ${FACE_EMBEDDING_IMAGE:-seafileltd/face-embedding:13.0-latest-cuda}
    container_name: face-embedding
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # ports:
    #   - 8886:8886
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - ${FACE_EMBEDDING_VOLUME:-/opt/face_embedding}/models:/models
      - ${FACE_EMBEDDING_VOLUME:-/opt/face_embedding}/logs:/logs
    environment:
      - FACE_EMBEDDING_SERVICE_KEY=${FACE_EMBEDDING_SERVICE_KEY:-${JWT_PRIVATE_KEY:?Variable is not set or empty}}
    networks:
      - seafile-net

networks:
  seafile-net:
    name: seafile-net
